### ISSUE TITLE
Loading Indicator

### ISSUE THREAD

**Issue by AdamBrodzinski** [meteor-utilities/Meteor-Griddle#1]
I've looked through source and didn't see any kind of a loading indicator for the times when Meteor will be fetching data.... I was thinking having a prop with a `loadingComponent` or something would be good and then if it's available then we can render that instead of griddle.

Thoughts? When I get around to migrating Tabular to this I would be open to pushing a PR.

Thanks!

**Comment by ryanlanciaux** [comment]
Do you think Griddle should take a loading (bool) prop and optional component to display when data is loading or would that be better served in the parent wrapper?

**Comment by SachaG** [comment]
@AdamBrodzinski yeah there's lots that could be improved here, it's more of a starting point. A loading indicator would be great. 

@ryanlanciaux good question, I guess either one could work. Another thought I had was doing some kind of "fake content" loading state, like Facebook does:

![https://images.thoughtbot.com/ember-alternate-states/facebook-loading-state.png](https://images.thoughtbot.com/ember-alternate-states/facebook-loading-state.png)

So the table would always display the same number of rows, but while the data is loading missing rows would just show these bars instead.

**Comment by AdamBrodzinski** [comment]
@SachaG ah yea that is interesting. If you could somehow do that plus some kind of spinner overlay I think that would be ideal.

What i've found is that if it's not super clear that it's loading... customers are like... were is my data?One was freaking out when tabular tables said no data available in table. normally this is never really seen (for long) but a slow connection made them think the data was toast.

Anyway I like the idea of having the fake content!

@ryanlanciaux I think in a non-meteor world with AJAX data populating the table it would be best to have the wrapper handle loading state, however this Meteor package manages the subscription to the collection data and it would be very hard to get a hook to properly do that from a parent. I think it makes sense to keep Griddle generic and have the Meteor 'glue package' handle it? BTW, just noticed you're the author of Griddle... thanks! great component!

**Comment by ryanlanciaux** [comment]
Thanks! And cool please let me know if there's anything that we could add that would help out here. 

We may examine adding a plugin for 1.0 to have the fake data while rows are loading but it shouldn't conflict with whatever happens in a wrapper (since it'll be an optional plugin).

**Comment by Siyfion** [comment]
I like the idea of some fake content, like Facebook does. I think that would certainly provide the best experience for the end users.

**Comment by hwillson** [comment]
Properties `externalLoadingComponent` (component displayed when data is loading) and `externalIsLoading` (if loading component should be shown instead of grid data) have been added to Griddle. I'll look into getting these wired up.

**Comment by hwillson** [comment]
I've wired `externalLoadingComponent` and `externalIsLoading` support up in the 1.3 branch (see  a7a177e). `externalIsLoading` is calculated from the subscription ready state. I've also updated the docs with a quick example.

**Comment by SachaG** [comment]
Awesome work @hwillson :)

**Comment by hwillson** [comment]
MeteorGriddle 1.0 is now available via Atmosphere, and supports `externalLoadingComponent`. Closing this off.
