### ISSUE TITLE
Feature Request: data transform

### ISSUE THREAD

**Issue by zeroasterisk** [meteor-utilities/Meteor-Griddle#10]
I'd love to get your recommended method to transform data before passing off to griddle.

Examples:
1. Translate an enum from a Number to a String
2. Transform a date object to a formatted string, with moment perhaps
3. Render a React component to render a specific cell, set of fields, or sub-document

I'm used to working with Tabular and DataTables... Griddle seems to be the new answer, but seems to be lacking some of the rendering customization options I'm used to with tabular.  Recommendations?

**Comment by SachaG** [comment]
Griddle lets you specify custom components for each column: http://griddlegriddle.github.io/Griddle/customization.html#customColumns

Does that answer your question?

**Comment by zeroasterisk** [comment]
Yeah - I found that about an hour after asking the question. Thanks a bunch!

**Comment by ouya99** [comment]
@zeroasterik

did you find a solution to a problem like customizing columns?

I have a tabular table which i try to convert to griddle. now I need to access object fields.. like street in an address object to display "street" in a griddle column. Any ideas?

  columns: [{
    data: "addresses.0.city",
    title: "city"
  }, {
    data: "addresses.0.street",
    title: "street"
  }, {

**Comment by zeroasterisk** [comment]
Yeah...

In the `columnMetadata` I tell it to render via a custom-component:

``` js
    {
      columnName: 'contactOps',
      displayName: 'Contact Ops',
      customComponent: GriddleOrgContact,
    },
    {
      columnName: 'contactBilling',
      displayName: 'Contact Billing',
      customComponent: GriddleOrgContact,
    },
    {
      columnName: 'contactSales',
      displayName: 'Contact Sales',
      customComponent: GriddleOrgContact,
    },
```

And then the custom component has access to the full record via `rowData` and the full "value" for this field's data is in `data`...

In my example it's a sub-document vs. an array of objects... 

``` js
/**
 * Cell for a Griddle
 */
import React from 'react';
import OrgContact from './OrgContact';

export default class GriddleOrgContact extends React.Component {
  render() {
    const { data } = this.props;
    const { emptyValue } = this.props.metadata;
    return <OrgContact contact={data} emptyValue={emptyValue} />;
  }
}

GriddleOrgContact.propTypes = {
  // value of field desired
  data: React.PropTypes.oneOfType([
    React.PropTypes.object,
    React.PropTypes.string,
  ]),
  rowData: React.PropTypes.object,
  // metadata can have optional extra params
  //   format = string, understood by moment.format()
  //     special value = "calendar" (default)
  //   emptyValue = string to use if no date data exists
  metadata: React.PropTypes.object,
};
```

But for an array of objects it might be something like:

``` js
    return <div>{data.map((node, i) => (
      <OrgContact key={i} contact={node} emptyValue={emptyValue} />;
    ))}</div>
```

**Comment by ouya99** [comment]
Thanks!

I managed to get it going with a "customComponent": LinkComponent :

var LinkComponent = React.createClass({
  render: function(){
    return <a> {this.props.data[0].street}</a>
  }
});

thanks for your more generic solution!
