### ISSUE TITLE
Immediate "Can't find npm module" error after "meteor add utilities:meteor-griddle"

### ISSUE THREAD

**Issue by tim-phillips** [meteor-utilities/Meteor-Griddle#15]
I get the following error after I run `meteor add utilities:meteor-griddle`:

`Can't find npm module 'react-addons-pure-render-mixin'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?`

**Comment by SachaG** [comment]
You need to `npm install --save griddle-react`

**Comment by tim-phillips** [comment]
Hmm, I still get the same error after running `npm install --save griddle-react`

**Comment by SachaG** [comment]
Then I guess you need to do `npm install --save react-addons-pure-render-mixin`
