### ISSUE TITLE
Browserify issue/Multiple React versions

### ISSUE THREAD

**Issue by SachaG** [meteor-utilities/Meteor-Griddle#2]
See https://github.com/meteor/react-packages/issues/168

**Comment by pram** [comment]
I was having the same and I think I've fixed it. I'm importing the npm directly into Meteor

in `/packages.json` add the following refs

```
"exposify": "0.5.0"
"griddle-react": "0.3.1"
```

in `client/lib/app.browserify.js` add the following

```
Griddle = require('griddle-react');
```

in `client/lib/app.browserify.options.json`

``` json
{
  "transforms": {
    "externalify": {
      "global": true,
      "external": {
        "react": "React.require",
        "react-dom": "React.require",
        "react/addons": "React"
      }
    },
    "exposify": {
      "global": true,
      "expose": {
        "underscore": "_",
        "jquery": "jQuery"
      }
    }
  }
}
```

Hopefully will give you some help

**Comment by oskareke** [comment]
@pram Didn't work for me, any chance you have any other ideas on this?

**Comment by pram** [comment]
No, sorry. Everything is working for me as expected.

**Comment by oskareke** [comment]
Ok. I did the following:

- Installed Griddle through NPM (using NPM 3.5.2 and Meteor 1.3-modules-beta.6)
- Imported MeteorGriddle.jsx as a regular component in TestGriddle.jsx
- Updated client/lib/app.browserify.options.json, client/lib/app.browserify.js and /packages.json as per @prams instructions

But I get:
`Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `TestGriddle`.`

**Comment by SachaG** [comment]
So actually, this package should probably not depend on the `react` Meteor package. I'll need to fix this.

**Comment by hwillson** [comment]
This is no longer an issue with the "1.3" branch (this can be closed when the 1.3 branch is merged to master).

**Comment by hwillson** [comment]
Tracking the 1.3 merge into master in #6.

**Comment by hwillson** [comment]
MeteorGriddle version 1.0 (supports Meteor 1.3) is now available via Atmosphere. It no longer uses Browserify, so this issue should be resolved.
