### ISSUE TITLE
 Only one page when using externalResultsPerPage

### ISSUE THREAD

**Issue by oskareke** [meteor-utilities/Meteor-Griddle#3]
When using externalResultsPerPage the limit gets set to that number in the publication and only one page of results gets delivered to the client, ignoring both externalMaxPage and maxPages. 

Did anyone else come across this issue?

**Comment by hwillson** [comment]
I see the same thing @oskareke - I'll take a look.

**Comment by hwillson** [comment]
Hi @oskareke - as a quick workaround; adding `useExternal` to your `MeteorGriddle` component call will fix this issue. For example:

```
<MeteorGriddle
  publication="gizmos.all"
  collection={gizmos}
  matchingResultsCount="gizmos-count"
  externalResultsPerPage={1}
  useExternal
/>
```

I'll look into wiring up a better solution for this shortly.

**Comment by oskareke** [comment]
@hwillson Nice one, thanks 👍

**Comment by hwillson** [comment]
Hi @oskareke - just following up on this. I have a new version ready to go that behaves as follows:
- Sets `useExternal` to be `false` by default.
- If `useExternal` is `false` (or not provided), will ignore all `external*` component props.
- If `useExternal` is `true` will use `external*` component props.

This will get rid of the broken behaviour you reported when not using `useExternal`, and I'll update the docs to make sure people know that `useExternal` is needed to leverage `external*` props. I'll post back when the new version is deployed. Thanks!

**Comment by hwillson** [comment]
Changes are now live (version 1.2.0). Thanks!
