### ISSUE TITLE
Merge 1.3 into master and get new version published

### ISSUE THREAD

**Issue by hwillson** [meteor-utilities/Meteor-Griddle#6]
Hi @SachaG - I'd like to get the 1.3 branch merged into master, and have the new version published (to Troposphere/Atmosphere). I was planning on:
1. Creating a new 1.2 branch from master.
2. Merging the 1.3 branch into master.
3. Bumping the package version to 1.0.0.
4. Removing the 1.3 branch.

I'll then be able to knock off most of the outstanding issues. Is this okay with you? If so I'll ping you when I'm done to have the new package published. Thanks!

**Comment by SachaG** [comment]
Yes, that's be awesome! Thanks for taking care of all this :)

**Comment by SachaG** [comment]
BTW if you give me your Meteor username I can give you access to the `utilities` org.

**Comment by hwillson** [comment]
Great, thanks @SachaG! I'll get this done tomorrow. Meteor username is "hwillson".

**Comment by hwillson** [comment]
I've completed steps 1 - 4 above. I've also upped the recommended dependencies to React 15. Unfortunately, the newly released Griddle 0.5.0 (to accommodate React 15) has an issue when used with Meteor 1.3. I've opened an issue https://github.com/GriddleGriddle/Griddle/issues/388. I'll look into finding a workaround in the meantime.

**Comment by ryanlanciaux** [comment]
Thanks @hwillson 0.5.1 of Griddle _should_ fix the issue. Very cool to see the updates here!

**Comment by hwillson** [comment]
Great @ryanlanciaux - 0.5.1 fixes it - thanks for the fast response!

**Comment by hwillson** [comment]
I've deployed 1.0 to Atmosphere. Closing this off - thanks all!
