### ISSUE TITLE
Debounce filter when useExternal is true

### ISSUE THREAD

**Issue by chrisknu** [meteor-utilities/Meteor-Griddle#8]
Currently the filter is set to hit the API on every keypress; a method to throttle/debounce this with a specified limit would be nice

**Comment by hwillson** [comment]
Hi @chrisknu - I'll take a look and get back to you shortly. Thanks!

**Comment by hwillson** [comment]
Hi @chrisknu - I have a new version ready to go for this that works as follows:
- When `useExternal` is `true`, you can use a new prop called `externalFilterDebounceWait` to set the filter debounce time.
- If `useExternal` is `true` and `externalFilterDebounceWait` is not set, a default time of 300 milliseconds is used.
- `externalFilterDebounceWait` only works when using external data (so when `useExternal` is `true`); For now we're not currently debouncing results all loaded at once (if the need arises though let me know).

I should have this new version published sometime tomorrow. Thanks!

**Comment by hwillson** [comment]
Changes are now live (version 1.2.0). Thanks!
