### ISSUE TITLE
Clarification - should the Meteor part of this be in the Page or Container?

### ISSUE THREAD

**Issue by zeroasterisk** [meteor-utilities/Meteor-Griddle#9]
With the (new-ish) concept of 3 layers of UI, should the Meteor part of this be setup in the container, with the collection and stuff passed down to the page/component level?

Can we get an example written in the style of the guide application structure?

THANKS!

**Comment by SachaG** [comment]
Well this package includes a container in itself, but I would probably still just use it directly in my components. It's true that ideally you want to separate out the container and the component, but the whole point of this package is to give you a single object that does both to save time.

**Comment by zeroasterisk** [comment]
ok - thanks for clarifying.
